#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Path: sta775s_changan_x64.py
# This file is generated by gen_pyclass_from_h_file.py
# Do not modify this file manually
# Generate python class from c++ header file
import ctypes


class RdrObjStsType_Replay_Fusion(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('RadarType_u8', ctypes.c_uint8),
        ('OtherFail_u8', ctypes.c_uint8),
        ('Reserved1', ctypes.c_uint16),
        ('RadarObj_num_u32', ctypes.c_uint32),
        ('RadarTimeHigh_u32', ctypes.c_uint32),
        ('RadarTimeLow_u32', ctypes.c_uint32),
        ('current_radar_time', ctypes.c_double),
    ]

class RdrObjType_Replay_Fusion(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('ID_u8', ctypes.c_uint8),
        ('ObjType_u8', ctypes.c_uint8),
        ('IsStationary_u8', ctypes.c_uint8),
        ('Reserved1', ctypes.c_uint8),
        ('PosX_f32', ctypes.c_float),
        ('PosY_f32', ctypes.c_float),
        ('RelVelX_f32', ctypes.c_float),
        ('RelVelY_f32', ctypes.c_float),
        ('RelAccX_f32', ctypes.c_float),
        ('RelAccY_f32', ctypes.c_float),
        ('AbsVelX_f32', ctypes.c_float),
        ('AbsVelY_f32', ctypes.c_float),
        ('AbsAccX_f32', ctypes.c_float),
        ('AbsAccY_f32', ctypes.c_float),
        ('ObstacleProb_f32', ctypes.c_float),
        ('Lenth_f32', ctypes.c_float),
        ('Width_f32', ctypes.c_float),
        ('Height_f32', ctypes.c_float),
        ('Heading_f32', ctypes.c_float),
        ('Age_u32', ctypes.c_uint32),
    ]

class RadarFsType_Replay(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('Range_f32', ctypes.c_float),
        ('FsConfidence_u8', ctypes.c_uint8),
        ('Reserved1_u8', ctypes.c_uint8),
        ('Reserved_u8_1', ctypes.c_uint8),
        ('Reserved_u8_2', ctypes.c_uint8),
    ]

class RadarFsListType_Replay(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('TimeStampHigh_u32', ctypes.c_uint32),
        ('TimeStampLow_u32', ctypes.c_uint32),
        ('RadarFsType_Replay_st', RadarFsType_Replay * 360),
    ]

class RdrObjListType_Replay_Fusion(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('SensorStatusFlags_st', RdrObjStsType_Replay_Fusion),
        ('SensorObject_st', RdrObjType_Replay_Fusion * 32),
        ('RadarFs', RadarFsListType_Replay),
    ]

