#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Path: sta775s.py
# This file is generated by gen_pyclass_from_h_file.py
# Do not modify this file manually
# Generate python class from c++ header file
import ctypes

MAX_TracePack_NUM = 64
MAX_ClusterPack_NUM = 40
MAX_CfarPack_NUM = 800
M_SECTIONSNUM_ALL = 128

class EthCfarMsg_Stru1_ACC(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('rangeIdx', ctypes.c_int16),
        ('dopplerIdx', ctypes.c_int16),
        ('peakVal', ctypes.c_int16),
        ('azimuthAngle', ctypes.c_int16),
        ('elevationAngle', ctypes.c_int16),
        ('speed', ctypes.c_int16),
        ('SNR', ctypes.c_int16),
        ('V_order', ctypes.c_int16),
        ('ambiangle2', ctypes.c_int16),
        ('ambiangle3', ctypes.c_int16),
    ]

class EthCfarPack_Str_ACC(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('CFAR_Array', EthCfarMsg_Stru1_ACC * MAX_CfarPack_NUM),
    ]

class ECU_Moni_Str_ACC(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('subFrameHeader', ctypes.c_uint16),
        ('subVersion', ctypes.c_uint8),
        ('subDataLength', ctypes.c_uint16),
        ('ego_speed_ic', ctypes.c_uint8),
        ('ego_SpeedValid', ctypes.c_uint8),
        ('ego_speed', ctypes.c_float),
        ('ego_accswitch', ctypes.c_uint8),
        ('ego_brake_press', ctypes.c_float),
        ('ego_brake_press_Valid', ctypes.c_uint8),
        ('ego_yawrate', ctypes.c_float),
        ('ego_YawRateValid', ctypes.c_uint8),
        ('ego_wiper', ctypes.c_uint8),
        ('ego_steer', ctypes.c_float),
        ('ego_steer_speed', ctypes.c_float),
        ('ego_SteerValid', ctypes.c_uint8),
        ('ego_throttle', ctypes.c_float),
        ('ego_brakepadal', ctypes.c_uint8),
        ('ego_indflag', ctypes.c_uint8),
        ('ego_error_fcw_flag', ctypes.c_uint8),
        ('ego_error_aeb_flag', ctypes.c_uint8),
        ('ego_error_acc_flag', ctypes.c_uint8),
        ('ego_ay', ctypes.c_float),
        ('ego_ax', ctypes.c_float),
        ('ego_cover_flag', ctypes.c_uint8),
        ('ego_hwt_dem_flag', ctypes.c_uint8),
        ('ego_standstill', ctypes.c_uint8),
        ('ego_v_desired', ctypes.c_float),
        ('ego_torque', ctypes.c_float),
        ('ego_torque_max', ctypes.c_float),
        ('ego_torque_min', ctypes.c_float),
        ('ego_override_flag', ctypes.c_uint8),
        ('ego_ratio', ctypes.c_float),
        ('ego_gear', ctypes.c_uint8),
        ('ego_gearvalid', ctypes.c_uint8),
        ('ego_ShiftPostionValid', ctypes.c_uint8),
        ('ego_shift', ctypes.c_uint8),
        ('ego_fcw_sensitivity_flag', ctypes.c_uint8),
        ('ego_aebswitch', ctypes.c_uint8),
        ('ego_AEBAvailable', ctypes.c_uint8),
        ('ego_AEBdecActive', ctypes.c_uint8),
        ('ego_HDC_STATUS', ctypes.c_uint8),
        ('ego_ABSFailStatus', ctypes.c_uint8),
        ('ego_OnlyABSActive', ctypes.c_uint8),
        ('ego_TCSFailStatus', ctypes.c_uint8),
        ('ego_TCSActive', ctypes.c_uint8),
        ('ego_EPB_Status', ctypes.c_uint8),
        ('ego_EPB_SwitchPosition', ctypes.c_uint8),
        ('ego_DriverDoorStatus', ctypes.c_uint8),
        ('ego_RightRearDoorStatus', ctypes.c_uint8),
        ('ego_PassengerDoorStatus', ctypes.c_uint8),
        ('ego_LeftRearDoorStatus', ctypes.c_uint8),
        ('ego_HoodStatus', ctypes.c_uint8),
        ('ego_DriverBuckleSwitchStatus', ctypes.c_uint8),
        ('ego_IndicatedDriverReqTorq', ctypes.c_float),
        ('ego_FrictionalTorq', ctypes.c_float),
        ('ego_TorqFailure', ctypes.c_uint8),
        ('ego_EngineFuelCutOff', ctypes.c_uint8),
        ('ego_TorqueConstant', ctypes.c_float),
        ('ego_EngineStatus', ctypes.c_uint8),
        ('ego_EngineLimpHome', ctypes.c_uint8),
        ('ego_EngineSpeedError', ctypes.c_uint8),
        ('ego_EngineSpeed', ctypes.c_float),
        ('ego_AccpedelError', ctypes.c_uint8),
        ('ego_AccReqPossible', ctypes.c_uint8),
        ('ego_EMS_QECACC', ctypes.c_uint8),
        ('ego_CruiseSwitchSET', ctypes.c_uint8),
        ('ego_CruiseSwitchResume', ctypes.c_uint8),
        ('ego_ESP_QDCACC', ctypes.c_uint8),
        ('ego_IP_QDashACCFail', ctypes.c_uint8),
        ('ego_DriveMode', ctypes.c_uint8),
        ('ego_Wheel_Speed_FR_Valid', ctypes.c_uint8),
        ('ego_Wheel_Speed_FR_Direction', ctypes.c_uint8),
        ('ego_Wheel_Speed_FR', ctypes.c_float),
        ('ego_Wheel_Speed_FL_Valid', ctypes.c_uint8),
        ('ego_Wheel_Speed_FL_Direction', ctypes.c_uint8),
        ('ego_Wheel_Speed_FL', ctypes.c_float),
        ('ego_Wheel_Speed_RR_Direction', ctypes.c_uint8),
        ('ego_Wheel_Speed_RR_Valid', ctypes.c_uint8),
        ('ego_Wheel_Speed_RR', ctypes.c_float),
        ('ego_Wheel_Speed_RL_Valid', ctypes.c_uint8),
        ('ego_Wheel_Speed_RL_Direction', ctypes.c_uint8),
        ('ego_Wheel_Speed_RL', ctypes.c_float),
        ('ego_HU_ACCObjEnable', ctypes.c_uint8),
        ('ego_HU_CruiseControlSet', ctypes.c_uint8),
        ('ego_BrakeDiscTempOverHeat', ctypes.c_uint8),
        ('ego_SRS_CrashOutputStatus', ctypes.c_uint8),
        ('ego_SRS_CrashOutputStatus_flag', ctypes.c_uint8),
        ('ego_ESP_ESPFunctionStatus', ctypes.c_uint8),
        ('ego_ESP_PrefillAvailable', ctypes.c_uint8),
        ('ego_ESP_ABAactive', ctypes.c_uint8),
        ('ego_ESP_ABAavailable', ctypes.c_uint8),
        ('ego_ESP_AWBavailable', ctypes.c_uint8),
        ('ego_ESP_CDD_Active', ctypes.c_uint8),
        ('ego_ESP_CDD_Available', ctypes.c_uint8),
        ('ego_ESP_VDCActive', ctypes.c_uint8),
        ('ego_ESP_BrakeForce', ctypes.c_uint8),
        ('ego_AEBErrorbyESP', ctypes.c_uint8),
        ('ego_AEBErrorbySAS', ctypes.c_uint8),
        ('ego_AEBErrorbySRS', ctypes.c_uint8),
        ('ego_AEBErrorbyEMS', ctypes.c_uint8),
        ('ego_AEBErrorbyTCU', ctypes.c_uint8),
        ('ego_AEBErrorbyOther', ctypes.c_uint8),
        ('ego_ACCError_ByEMS', ctypes.c_uint8),
        ('ego_ACCError_ByBCM', ctypes.c_uint8),
        ('ego_ACCError_ByTCU', ctypes.c_uint8),
        ('ego_ACCError_ByIP', ctypes.c_uint8),
        ('ego_ACCError_BySRS', ctypes.c_uint8),
        ('ego_ACCError_ByMFS', ctypes.c_uint8),
        ('ego_ACCError_ByEPB', ctypes.c_uint8),
        ('ego_HU_NavStatus', ctypes.c_uint8),
        ('ego_EEyeSpeedLimit', ctypes.c_uint8),
        ('ego_NavSpeedLimitStatus', ctypes.c_uint8),
        ('ego_NavCurrentRoadType', ctypes.c_uint8),
        ('ego_HU_RampInfo', ctypes.c_uint8),
        ('ego_HU_RampDistance', ctypes.c_float),
        ('ego_HU_NavGuiganceStatus', ctypes.c_uint8),
        ('ego_HU_TollInfo', ctypes.c_uint8),
        ('ego_HU_TollDis', ctypes.c_float),
        ('ego_HU_EnterTunnelInfo', ctypes.c_uint8),
        ('ego_HU_TunnelDistance', ctypes.c_float),
        ('ego_HU_TunnelLength', ctypes.c_float),
        ('ego_HU_CSL_Error', ctypes.c_uint8),
        ('ego_ECM_ACC_CancelSw', ctypes.c_uint8),
        ('ego_HazardLightSwSts', ctypes.c_uint8),
        ('reserved', ctypes.c_uint8 * 50),
        ('subCheckSum', ctypes.c_uint8),
    ]

class LostNumAll_STBC_Type_Str_ACC(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('lost_num_all', ctypes.c_byte * 12),
        ('STBC_TypeS', ctypes.c_byte * 1),
        ('STBC_TypeT', ctypes.c_byte * 1),
        ('STBC_TypeB', ctypes.c_byte * 1),
        ('STBC_TypeC', ctypes.c_byte * 1),
    ]

class Box_Info_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('box_length', ctypes.c_bool),
        ('box_width', ctypes.c_bool * 10),
        ('box_height', ctypes.c_bool * 10),
    ]

class Score_LostNum_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('score', ctypes.c_byte * 4),
        ('LostNum', ctypes.c_byte * 4),
    ]

class moveState_Type_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('moveState', ctypes.c_byte * 4),
        ('TarType', ctypes.c_byte * 4),
    ]

class Target_TRACE_5s(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('Index', ctypes.c_uint8),
        ('Ry', ctypes.c_int16),
        ('Rx', ctypes.c_int16),
        ('height', ctypes.c_int16),
        ('BoxInfo', Box_Info_Str),
        ('cross_speed', ctypes.c_int16),
        ('longitu_speed', ctypes.c_int16),
        ('Aceler_Y', ctypes.c_int16),
        ('Aceler_X', ctypes.c_int16),
        ('dis_clu', ctypes.c_uint16),
        ('ang_clu', ctypes.c_int16),
        ('evangle_clu', ctypes.c_int16),
        ('speed_clu', ctypes.c_int16),
        ('peakVal', ctypes.c_uint16),
        ('SNR', ctypes.c_uint8),
        ('RCS', ctypes.c_int16),
        ('lifeTime', ctypes.c_uint16),
        ('score_lostNum', Score_LostNum_Str),
        ('Multipath', ctypes.c_uint8),
        ('moveState_Type', moveState_Type_Str),
        ('recognization_target', ctypes.c_uint8),
        ('obstacle', ctypes.c_uint8),
        ('ExistProb', ctypes.c_uint8),
        ('Yaw', ctypes.c_int16),
        ('measure_point', ctypes.c_uint8),
        ('Y_distance_std', ctypes.c_int16),
        ('Y_speed_std', ctypes.c_int16),
        ('Y_Acc_std', ctypes.c_int16),
        ('X_distance_std', ctypes.c_int16),
        ('X_speed_std', ctypes.c_int16),
        ('X_Acc_std', ctypes.c_int16),
        ('lost_num_all', ctypes.c_uint16),
        ('clusterUid', ctypes.c_uint8),
        ('uid_start', ctypes.c_uint8),
        ('vyAbs', ctypes.c_int16),
        ('vxAbs', ctypes.c_int16),
    ]

class Target_TRACE_Str_ACC(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('subFrameHeader', ctypes.c_uint16),
        ('subVersion', ctypes.c_uint8),
        ('subDataLength', ctypes.c_uint16),
        ('periodBitNum_Trace', ctypes.c_uint16),
        ('maxVldTraceNum', ctypes.c_uint16),
        ('trace', Target_TRACE_5s * MAX_TracePack_NUM),
        ('subCheckSum', ctypes.c_uint8),
    ]

class clusterId_Type_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('clusterId', ctypes.c_byte * 6),
        ('IsRectOrDbscan', ctypes.c_byte * 2),
    ]

class Height_Flag_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('height', ctypes.c_byte * 13),
        ('cfar_flag', ctypes.c_byte * 3),
    ]

class Target_CLUSTER(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('clusterId_Type', clusterId_Type_Str),
        ('traceId', ctypes.c_uint8),
        ('Ry', ctypes.c_int16),
        ('Rx', ctypes.c_uint16),
        ('range', ctypes.c_uint16),
        ('Rz', ctypes.c_int16),
        ('speed', ctypes.c_int16),
        ('peakVal', ctypes.c_int16),
        ('azimuthAngle', ctypes.c_int16),
        ('elevationAngle', ctypes.c_int16),
        ('SNR', ctypes.c_uint8),
        ('rangeIdx', ctypes.c_uint16),
        ('element_num', ctypes.c_uint8),
        ('cornersInfo', ctypes.c_int16 * 8),
        ('Height_CfarFlag', Height_Flag_Str),
        ('reserve', ctypes.c_int16),
    ]

class Target_CLUSTER_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('subFrameHeader', ctypes.c_uint16),
        ('subVersion', ctypes.c_uint8),
        ('subDataLength', ctypes.c_uint16),
        ('periodBitNum_Cluster', ctypes.c_uint16),
        ('maxVldClusterNum', ctypes.c_uint16),
        ('cluster', Target_CLUSTER * MAX_ClusterPack_NUM),
        ('subCheckSum', ctypes.c_uint8),
    ]

class SingleTarget_MicroDoppler_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('MD_Tar_Trace_Index', ctypes.c_uint8),
        ('MD_Tar_Range_Bin', ctypes.c_uint8),
        ('MD_Tar_frame_num', ctypes.c_uint8),
        ('MD_Tar_state', ctypes.c_uint8),
        ('MD_Tar_type', ctypes.c_uint8),
        ('Tar_MD_Data', ctypes.c_uint8 * 95),
        ('MD_Reserve', ctypes.c_uint8 * 28),
    ]

class Target_MicroDoppler_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('SingleTarget_MicroDoppler', SingleTarget_MicroDoppler_Str * 30),
        ('Reserve', ctypes.c_uint8 * 1280),
    ]

class evAngle_motionFlg_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('elevationAngle', ctypes.c_byte * 12),
        ('motion_flg', ctypes.c_byte * 4),
    ]

class Vorder_cfarflag_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('V_order', ctypes.c_byte * 3),
        ('cfar_flag', ctypes.c_byte * 5),
    ]

class rangeIdx_clusterId_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('rangeIdx', ctypes.c_byte * 10),
        ('clusterId', ctypes.c_byte * 6),
    ]

class Target_CFAR(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('dopplerIdx', ctypes.c_uint8),
        ('moveState', ctypes.c_uint8),
        ('peakVal', ctypes.c_uint8),
        ('azimuthAngle', ctypes.c_int16),
        ('evAngle_motionFlg', evAngle_motionFlg_Str),
        ('speed', ctypes.c_int16),
        ('SNR', ctypes.c_uint8),
        ('Vorder_cfarflag', Vorder_cfarflag_Str),
        ('rangeIdx_clusterId', rangeIdx_clusterId_Str),
        ('Rx', ctypes.c_uint16),
        ('Ry', ctypes.c_int16),
        ('Rz', ctypes.c_int16),
        ('RCS', ctypes.c_int16),
        ('traceId', ctypes.c_uint8),
        ('Range', ctypes.c_uint16),
    ]

class Target_CFAR_Str_ACC(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('subFrameHeader', ctypes.c_uint16),
        ('subVersion', ctypes.c_uint8),
        ('subDataLength', ctypes.c_uint16),
        ('periodBitNum_Cfar', ctypes.c_uint16),
        ('maxVldCfarNum', ctypes.c_uint16),
        ('cfar', Target_CFAR * MAX_CfarPack_NUM),
        ('subCheckSum', ctypes.c_uint8),
    ]

class LeakOut_Amp_T_ACC(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('LeakOut_Amp0', ctypes.c_uint8 * 18),
        ('LeakOut_Amp1', ctypes.c_uint8 * 18),
        ('LeakOut_Amp2', ctypes.c_uint8 * 18),
        ('LeakOut_Amp3', ctypes.c_uint8 * 18),
    ]

class Clutter_Block_T_ACC(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('Clutter_Amp', ctypes.c_uint16),
        ('Clutter_X', ctypes.c_uint16),
        ('Clutter_Y', ctypes.c_uint16),
        ('Blockage_Flag', ctypes.c_uint8),
    ]

class AutoAngle_T_ACC(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('Azi_Angle_Num', ctypes.c_uint8),
        ('Azi_Rec_Angle', ctypes.c_int16),
        ('Prest_Azi_Angle', ctypes.c_int16),
        ('Azi_Misalign_Flag', ctypes.c_uint8),
        ('Pitch_Angle_Num', ctypes.c_uint8),
        ('Pitch_Rec_Angle', ctypes.c_int16),
        ('Prest_Pitch_Angle', ctypes.c_int16),
        ('Pitch_Misalign_Flag', ctypes.c_uint8),
    ]

class RGC_Result_Str_ACC(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('RGC_RoadGradient', ctypes.c_float),
        ('RGC_RoadGradientFlag', ctypes.c_uint8),
        ('RGC_RoadConfidence', ctypes.c_uint8),
    ]

class MonitorData_DSP_t_ACC(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('subFrameHeader', ctypes.c_uint16),
        ('versions', ctypes.c_uint8),
        ('subDataLength', ctypes.c_uint16),
        ('Clutter_Block', Clutter_Block_T_ACC),
        ('AutoAngle_Para', AutoAngle_T_ACC),
        ('RGC_Result', RGC_Result_Str_ACC),
        ('LeakOut_Amp', LeakOut_Amp_T_ACC),
        ('reserved', ctypes.c_uint8 * 26),
        ('subCheckSum', ctypes.c_uint8),
    ]

class CoverBase_Str_ACC(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('R', ctypes.c_uint8 * 10),
    ]

class CoverRD_Str_ACC(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('subFrameHeader', ctypes.c_uint16),
        ('subVersion', ctypes.c_uint8),
        ('subDataLength', ctypes.c_uint16),
        ('RDValue', ctypes.c_uint8 * 110),
        ('subCheckSum', ctypes.c_uint8),
    ]

class Protocol_Head_Str_ACC(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('HeadCode1', ctypes.c_uint16),
        ('totalVersion', ctypes.c_uint8),
        ('DataLength', ctypes.c_uint32),
    ]

class Frame_Head_Date_Str_ACC(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('subFrameHeader', ctypes.c_uint16),
        ('subVersion', ctypes.c_uint8),
        ('subDataLength', ctypes.c_uint16),
        ('RadarState', ctypes.c_uint8),
        ('TraceNum', ctypes.c_uint8),
        ('ClusterNum', ctypes.c_uint8),
        ('CFAR_Num', ctypes.c_uint16),
        ('FrameCount', ctypes.c_uint32),
        ('frametime', ctypes.c_float),
        ('CarSpeed', ctypes.c_float),
        ('CarYawrate', ctypes.c_float),
        ('SteerWheelAngle', ctypes.c_float),
        ('SteerWheelSpeed', ctypes.c_float),
        ('DSP_Acceleration_X', ctypes.c_float),
        ('DSP_Acceleration_Y', ctypes.c_float),
        ('CarRadius', ctypes.c_float),
        ('Scene_VRU_Ped', ctypes.c_uint8),
        ('SystemClockHeader', ctypes.c_uint8),
        ('SystemClockHour', ctypes.c_uint8),
        ('SystemClockMinute', ctypes.c_uint8),
        ('SystemClockSec', ctypes.c_uint8),
        ('SystemClockMilliSec', ctypes.c_uint16),
        ('PointCoordinate', ctypes.c_uint8),
        ('SceneryMode', ctypes.c_uint8),
        ('RTK_TestMode', ctypes.c_uint8),
        ('fitEgoSpeed', ctypes.c_float),
        ('fitSpeed_validFlag', ctypes.c_uint8),
        ('Reserved', ctypes.c_uint8 * 19),
        ('subCheckSum', ctypes.c_uint8),
    ]

class RF_ConfigPara_Str_ACC(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('subFrameHeader', ctypes.c_uint16),
        ('subVersion', ctypes.c_uint8),
        ('subDataLength', ctypes.c_uint16),
        ('rangeResolution', ctypes.c_float),
        ('dopplerResolution', ctypes.c_float),
        ('M_FFT_NUM_1_D_NARROW', ctypes.c_uint16),
        ('M_FFT_NUM_2_D_NARROW', ctypes.c_uint16),
        ('M_FFT_NUM_3_D_NARROW', ctypes.c_uint16),
        ('centerCarrierFreq', ctypes.c_float),
        ('bandwidth', ctypes.c_float),
        ('lamda', ctypes.c_float),
        ('speedofLight', ctypes.c_float),
        ('PRT', ctypes.c_float),
        ('FrameTime', ctypes.c_uint16),
        ('SampleRateHz', ctypes.c_float),
        ('startFreqConst', ctypes.c_float),
        ('stepFreqdelta', ctypes.c_float),
        ('SampleNum', ctypes.c_uint16),
        ('ChipNum', ctypes.c_uint16),
        ('bpmCodeNum', ctypes.c_uint8),
        ('numTxAntennas', ctypes.c_uint8),
        ('numRxAntennas', ctypes.c_uint8),
        ('installYaw', ctypes.c_float),
        ('installPitch', ctypes.c_float),
        ('installY', ctypes.c_float),
        ('installX', ctypes.c_float),
        ('installZ', ctypes.c_float),
        ('installHeight', ctypes.c_float),
        ('ConnectDirec', ctypes.c_uint8),
        ('InstallSite', ctypes.c_uint8),
        ('LengthVehicle', ctypes.c_float),
        ('WidthVehicle', ctypes.c_float),
        ('MultiPrtFlag', ctypes.c_uint8),
        ('AntennaStatus', ctypes.c_uint8),
        ('Reserved', ctypes.c_uint8 * 20),
        ('subCheckSum', ctypes.c_uint8),
    ]

class Voltage_Date_Str_ACC(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('DSP_HandleTime', ctypes.c_uint8 * 11),
        ('RadarStaCode', ctypes.c_uint32),
        ('TimeStamp', ctypes.c_uint32),
        ('SequenceNum', ctypes.c_uint32),
        ('WorkMode', ctypes.c_uint8),
        ('VeicleSensorStaCode', ctypes.c_uint8),
        ('RangeBias', ctypes.c_float),
    ]

class Roadside_Date_Base_Str_ACC(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('roadside_factor_a', ctypes.c_float),
        ('roadside_factor_b', ctypes.c_float),
        ('roadside_factor_c', ctypes.c_float),
        ('roadside_flag', ctypes.c_int8),
        ('roadside_frame', ctypes.c_uint8),
        ('roadside_lower_flag', ctypes.c_uint8),
        ('roadside_upper_flag', ctypes.c_uint8),
        ('roadside_status', ctypes.c_uint8),
        ('roadside_confidence', ctypes.c_uint8),
    ]

class GroundPointInfo_PackOut_in(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('X', ctypes.c_uint8),
        ('Y', ctypes.c_uint8),
        ('v_order', ctypes.c_int8),
        ('fudu', ctypes.c_uint8),
        ('angle', ctypes.c_int16),
        ('evangle', ctypes.c_int16),
        ('speed', ctypes.c_float),
    ]

class Radar_Status_Date_Str_ACC(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('subFrameHeader', ctypes.c_uint16),
        ('versions', ctypes.c_uint8),
        ('subDataLength', ctypes.c_uint16),
        ('WorkMode', ctypes.c_uint8),
        ('roadside_factor_a', ctypes.c_float),
        ('roadside_factor_b', ctypes.c_float),
        ('roadside_factor_c', ctypes.c_float),
        ('roadside_flag', ctypes.c_int8),
        ('roadside_frame', ctypes.c_uint8),
        ('roadside_lower_flag', ctypes.c_uint8),
        ('roadside_upper_flag', ctypes.c_uint8),
        ('left_status', ctypes.c_uint8),
        ('left_confidence', ctypes.c_uint8),
        ('right_roadside_factor_a', ctypes.c_float),
        ('right_roadside_factor_b', ctypes.c_float),
        ('right_roadside_factor_c', ctypes.c_float),
        ('right_roadside_flag', ctypes.c_int8),
        ('right_roadside_frame', ctypes.c_uint8),
        ('right_roadside_lower_flag', ctypes.c_uint8),
        ('right_roadside_upper_flag', ctypes.c_uint8),
        ('right_status', ctypes.c_uint8),
        ('right_confidence', ctypes.c_uint8),
        ('fixAngle_Azi', ctypes.c_int16),
        ('fixAngle_Pitch', ctypes.c_int16),
        ('Fix_Angle_Horizontal', ctypes.c_int16),
        ('Fix_Angle_Vertical', ctypes.c_int16),
        ('code_cmd', ctypes.c_uint8),
        ('RadarCalibrationStatus', ctypes.c_uint8),
        ('PowerADC', ctypes.c_uint16),
        ('PowerCnt', ctypes.c_uint32),
        ('dsp_temp', ctypes.c_uint8),
        ('hwa_temp', ctypes.c_uint8),
        ('hsm_temp', ctypes.c_uint8),
        ('radarTemperature', ctypes.c_uint8),
        ('hardwareVersion', ctypes.c_uint8 * 3),
        ('softwareVersion', ctypes.c_uint8 * 3),
        ('BTVersion', ctypes.c_uint8 * 3),
        ('HashAPP', ctypes.c_uint8 * 8),
        ('HashALG', ctypes.c_uint8 * 8),
        ('Rn_PackOut1', GroundPointInfo_PackOut_in * 6),
        ('Reserved', ctypes.c_uint8 * 40),
        ('subCheckSum', ctypes.c_uint8),
    ]

class DSP_ACC_AEB_CarInfo_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('A_VehiclSpeed', ctypes.c_float),
        ('A_VehiclSpeed_IC', ctypes.c_uint8),
        ('A_MasterCylinderPressure', ctypes.c_uint16),
        ('A_YawRate', ctypes.c_float),
        ('A_SteeringWheelAngle', ctypes.c_float),
        ('A_SteeringWheelSpeed', ctypes.c_float),
        ('A_AccelerationPedalPos', ctypes.c_uint16),
        ('A_BrakePedalSt', ctypes.c_uint8),
        ('A_WiperSpeed_Front', ctypes.c_uint8),
        ('A_TurningLigntSt', ctypes.c_uint8),
        ('A_VehicleLostFlg', ctypes.c_uint8),
        ('A_Acceleration_X', ctypes.c_float),
        ('A_Hwt_dem', ctypes.c_uint8),
        ('A_v_desired', ctypes.c_uint8),
        ('A_CombustionTorque', ctypes.c_uint16),
        ('A_MaximumTorque', ctypes.c_uint16),
        ('A_MinimumTorque', ctypes.c_uint16),
        ('Reserved', ctypes.c_uint8 * 101),
    ]

class Alarm_AEB_T_ACC(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('ABP_Flag', ctypes.c_uint8),
        ('FCW_Flag', ctypes.c_uint8),
        ('AWB_Flag', ctypes.c_uint8),
        ('AEB_Flag', ctypes.c_uint8),
    ]

class AEB_TempInfo_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('AEB_out_lock_targetid', ctypes.c_uint8),
        ('AEB_out_final_ttc_min', ctypes.c_float),
        ('AEB_out_brake_dec', ctypes.c_float),
        ('AEB_out_brake_req', ctypes.c_uint8),
        ('AEB_out_abp_final_flag', ctypes.c_uint8),
        ('AEB_out_awb_final_flag', ctypes.c_uint8),
        ('AEB_out_awb_level', ctypes.c_uint8),
        ('AEB_out_VehilceHoldReq', ctypes.c_uint8),
        ('AEB_out_CtrlType', ctypes.c_uint8),
        ('AEB_out_AEBEnable', ctypes.c_uint8),
        ('AEB_out_TargetDetection', ctypes.c_uint8),
        ('AEB_out_TargetType', ctypes.c_uint8),
        ('AEB_out_TargetLngRange', ctypes.c_float),
        ('AEB_out_TargetRelSpeed', ctypes.c_float),
        ('AEB_out_TargetLatRange', ctypes.c_float),
        ('AEB_out_Status', ctypes.c_uint8),
        ('AEB_out_TextInfo', ctypes.c_uint8),
        ('AEB_out_Targetmode', ctypes.c_uint8),
        ('AEB_out_FCWSettingStatus', ctypes.c_uint8),
        ('AEB_out_FCWActive', ctypes.c_uint8),
        ('AEB_out_FCWLatentWarning', ctypes.c_uint8),
        ('AEB_out_FCWwaring', ctypes.c_uint8),
        ('AEB_outABAlevel', ctypes.c_uint8),
        ('AEB_outABAActive', ctypes.c_uint8),
        ('AEB_outEmergencyLightingRequest', ctypes.c_uint8),
        ('Reserved', ctypes.c_uint8 * 36),
    ]

class Acc_PidParaPack_Str_DEF(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('kp', ctypes.c_float),
        ('ki', ctypes.c_float),
        ('kd', ctypes.c_float),
    ]

class AccParaSetMonitor_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('Acc_PidParaPack_Str', Acc_PidParaPack_Str_DEF * 100),
    ]

class ACC_Logic_out_Para_str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('ACC_Status', ctypes.c_uint8),
        ('ACC_Deceleration_Req_Logic', ctypes.c_uint8),
        ('ACC_Deceleration_Val_Logic', ctypes.c_float),
        ('ACC_Acceleration_Req_Logic', ctypes.c_uint8),
        ('ACC_Acceleration_TorqueVal_Logic', ctypes.c_float),
        ('ACC_Standstill_request_Logic', ctypes.c_uint8),
        ('ACC_Object_captured_status_Logic', ctypes.c_uint8),
        ('ACC_Take_over_request_Logic', ctypes.c_uint8),
        ('ACC_Target_distance_Logic', ctypes.c_uint8),
        ('ACC_Desire_speed_Logic', ctypes.c_uint8),
    ]

class Acc_EgoVehCurveInfo_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('coef_a', ctypes.c_float),
        ('coef_b', ctypes.c_float),
        ('coef_c', ctypes.c_float),
        ('max_y', ctypes.c_float),
        ('min_y', ctypes.c_float),
    ]

class Acc_VehTrackCurve_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('packEgoCurve_coef', Acc_EgoVehCurveInfo_Str * 2),
        ('packTargetCurve_coef', Acc_EgoVehCurveInfo_Str * 3),
        ('EgoVehCurveConfidence', ctypes.c_uint8),
        ('EgoVehCurveStatus', ctypes.c_uint8),
        ('reserved', ctypes.c_uint8 * 16),
    ]

class ACC_TempInfo_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('ACC_out_dec_req', ctypes.c_uint8),
        ('ACC_out_dec', ctypes.c_float),
        ('ACC_out_torque_req', ctypes.c_uint8),
        ('ACC_out_torque', ctypes.c_float),
        ('ACC_out_sd_req', ctypes.c_uint8),
        ('ACC_out_tarspeed_des', ctypes.c_float),
        ('ACC_out_tardis_stage', ctypes.c_uint8),
        ('ACC_out_takeover_req', ctypes.c_uint8),
        ('ACC_out_tarcaptured_flag', ctypes.c_uint8),
        ('ACC_out_driveoff_flag', ctypes.c_uint8),
        ('ACC_out_EmergencyDataRrdReq', ctypes.c_uint8),
        ('ACC_out_ACCMode', ctypes.c_uint8),
        ('ACC_out_FuelCutOffPrevention', ctypes.c_uint8),
        ('ACC_out_DistanceLevel', ctypes.c_uint8),
        ('ACC_out_ACCTargetLngRange', ctypes.c_float),
        ('ACC_out_ACCTargetType', ctypes.c_uint8),
        ('ACC_out_TextInfoForDriver', ctypes.c_uint8),
        ('ACC_out_ACCTargetRelSpd', ctypes.c_float),
        ('ACC_out_ACCTargetLatRange', ctypes.c_float),
        ('ACC_out_ACCTargetID', ctypes.c_uint8),
        ('ACC_out_TCUCreepProhibition', ctypes.c_uint8),
        ('ACC_ACCObjSoundEnable', ctypes.c_uint8),
        ('ACC_CruiseSetStatus', ctypes.c_uint8),
        ('ACC_Voiceinfo', ctypes.c_uint8),
        ('ACC_out_EPBrequest', ctypes.c_uint8),
        ('ACC_out_HostTargetDetection', ctypes.c_uint8),
        ('ACC_outCSL_CSLAEnableStatus', ctypes.c_uint8),
        ('ACC_outCSL_CSLSetReq', ctypes.c_uint8),
        ('ACC_outCSL_Valid_Flag', ctypes.c_uint8),
        ('ACC_outCSL_Out_Spd', ctypes.c_uint8),
        ('ACC_outCSL_SpdLimit_Type', ctypes.c_uint8),
        ('TJA_ACC_SelSts', ctypes.c_uint8),
        ('TJA_ICA_InterSysInfoDisp', ctypes.c_uint8),
        ('TJA_ICA_Sts', ctypes.c_uint8),
        ('ACC_FctSts', ctypes.c_uint8),
        ('ACC_out_ACCTargetAbsoluteSpd', ctypes.c_float),
        ('ACC_out_Expectdistance', ctypes.c_float),
        ('reserved', ctypes.c_uint8 * 36),
    ]

class ACC_MidData_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('Acc_middata_one', ctypes.c_float),
        ('Acc_middata_two', ctypes.c_float),
        ('Acc_middata_three', ctypes.c_float),
        ('Acc_middata_four', ctypes.c_float),
        ('Acc_middata_five', ctypes.c_float),
        ('Acc_middata_six', ctypes.c_float),
        ('Acc_middata_seven', ctypes.c_float),
        ('Acc_middata_eight', ctypes.c_float),
        ('Acc_middata_nine', ctypes.c_float),
        ('Acc_middata_ten', ctypes.c_float),
        ('Acc_middata_eleven', ctypes.c_float),
        ('Acc_middata_twelve', ctypes.c_float),
        ('Acc_middata_thirteen', ctypes.c_float),
        ('Acc_middata_fourteen', ctypes.c_float),
        ('Acc_middata_fifteen', ctypes.c_float),
        ('Acc_middata_sixteen', ctypes.c_float),
        ('Acc_middata_seventeen', ctypes.c_float),
        ('Acc_middata_eighteen', ctypes.c_float),
        ('Acc_middata_nineteen', ctypes.c_float),
        ('Acc_middata_twenty', ctypes.c_float),
        ('Acc_middata_twenty_one', ctypes.c_float),
        ('Acc_middata_twenty_two', ctypes.c_float),
        ('Acc_middata_twenty_three', ctypes.c_float),
        ('Acc_middata_twenty_four', ctypes.c_float),
        ('Acc_middata_twenty_five', ctypes.c_float),
        ('Acc_middata_twenty_six', ctypes.c_float),
        ('Acc_middata_twenty_seven', ctypes.c_float),
        ('Acc_middata_twenty_eight', ctypes.c_float),
        ('Acc_middata_twenty_nine', ctypes.c_float),
        ('Acc_middata_thirty', ctypes.c_float),
        ('reserve', ctypes.c_uint8 * 16),
    ]

class ACC_TarId_Info_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('targetid_lock', ctypes.c_uint8),
        ('tartype_lock', ctypes.c_uint8),
        ('lock_differ', ctypes.c_uint16),
        ('targetid_ptl_f', ctypes.c_uint8),
        ('tartype_ptl_f', ctypes.c_uint8),
        ('ptlf_differ', ctypes.c_uint16),
        ('targetid_ptl_l', ctypes.c_uint8),
        ('tartype_ptl_l', ctypes.c_uint8),
        ('ptll_differ', ctypes.c_uint16),
        ('targetid_ptl_r', ctypes.c_uint8),
        ('tartype_ptl_r', ctypes.c_uint8),
        ('ptlr_differ', ctypes.c_uint16),
        ('reserved', ctypes.c_uint8 * 16),
    ]

class ADAS_PathPre_Info_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('coef_ego_a', ctypes.c_float),
        ('coef_ego_b', ctypes.c_float),
        ('coef_ego_c', ctypes.c_float),
        ('coef_road_a', ctypes.c_float),
        ('coef_road_b', ctypes.c_float),
        ('coef_road_c', ctypes.c_float),
        ('coef_fuse_y', ctypes.c_float),
        ('fuse_flag', ctypes.c_uint8),
        ('path_flag', ctypes.c_uint8),
        ('reserved', ctypes.c_uint8 * 16),
    ]

class AEB_MidData_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('Aeb_middata_one', ctypes.c_float),
        ('Aeb_middata_two', ctypes.c_float),
        ('Aeb_middata_three', ctypes.c_float),
        ('Aeb_middata_four', ctypes.c_float),
        ('Aeb_middata_five', ctypes.c_float),
        ('Aeb_middata_six', ctypes.c_float),
        ('Aeb_middata_seven', ctypes.c_float),
        ('Aeb_middata_eight', ctypes.c_float),
        ('Aeb_middata_nine', ctypes.c_float),
        ('Aeb_middata_ten', ctypes.c_float),
        ('Aeb_middata_eleven', ctypes.c_float),
        ('Aeb_middata_twelve', ctypes.c_float),
        ('Aeb_middata_thirteen', ctypes.c_float),
        ('Aeb_middata_fourteen', ctypes.c_float),
        ('Aeb_middata_fifteen', ctypes.c_float),
        ('Aeb_middata_sixteen', ctypes.c_float),
        ('Aeb_middata_seventeen', ctypes.c_float),
        ('Aeb_middata_eighteen', ctypes.c_float),
        ('Aeb_middata_nineteen', ctypes.c_float),
        ('Aeb_middata_twenty', ctypes.c_float),
        ('Aeb_middata_twenty_one', ctypes.c_float),
        ('Aeb_middata_twenty_two', ctypes.c_float),
        ('Aeb_middata_twenty_three', ctypes.c_float),
        ('Aeb_middata_twenty_four', ctypes.c_float),
        ('Aeb_middata_twenty_five', ctypes.c_float),
        ('Aeb_middata_twenty_six', ctypes.c_float),
        ('Aeb_middata_twenty_seven', ctypes.c_float),
        ('Aeb_middata_twenty_eight', ctypes.c_float),
        ('Aeb_middata_twenty_nine', ctypes.c_float),
        ('Aeb_middata_thirty', ctypes.c_float),
        ('reserved', ctypes.c_uint8 * 128),
    ]

class ADAS_Monitor_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('subFrameHeader', ctypes.c_uint16),
        ('versions', ctypes.c_uint8),
        ('subDataLength', ctypes.c_uint16),
        ('ACC_TempInfo', ACC_TempInfo_Str),
        ('AEB_TempInfo', AEB_TempInfo_Str),
        ('ParaSetInfo', AccParaSetMonitor_Str),
        ('ACC_MiddataInfo', ACC_MidData_Str),
        ('ACC_TarID_Info', ACC_TarId_Info_Str),
        ('PathPre_Info', ADAS_PathPre_Info_Str),
        ('VehTrackCurve_Info', Acc_VehTrackCurve_Str),
        ('AEB_MiddataInfo', AEB_MidData_Str),
        ('subCheckSum', ctypes.c_uint8),
    ]

class FS_Result_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('lateralRoadIndex', ctypes.c_uint8),
        ('longituRoadIndex', ctypes.c_uint8),
    ]

class FS_Result_Str2(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('Range', ctypes.c_byte * 10),
        ('Confidence', ctypes.c_byte * 2),
        ('MoveState', ctypes.c_byte * 4),
    ]

class FreeSpaceData_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('subFrameHeader', ctypes.c_uint16),
        ('versions', ctypes.c_uint8),
        ('subDataLength', ctypes.c_uint16),
        ('lateralStartRange', ctypes.c_int8),
        ('longituStartRange', ctypes.c_uint8),
        ('lateralSize', ctypes.c_uint8),
        ('longitudinalSize', ctypes.c_uint8),
        ('lateralStep', ctypes.c_uint8),
        ('longitudinalStep', ctypes.c_uint8),
        ('Reserved1', ctypes.c_uint8 * 22),
        ('FS_Result1', FS_Result_Str * M_SECTIONSNUM_ALL),
        ('FS_Result2', FS_Result_Str2 * 360),
        ('Reserved2', ctypes.c_uint8 * 280),
        ('subCheckSum', ctypes.c_uint8),
    ]

class RD_Data_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('subFrameHeader', ctypes.c_uint16),
        ('versions', ctypes.c_uint8),
        ('subDataLength', ctypes.c_uint16),
        ('Rn_PackOut20', GroundPointInfo_PackOut_in * 5),
        ('RDValue', ctypes.c_uint8 * 50),
        ('subCheckSum', ctypes.c_uint8),
    ]

class TempData_Monitor_Str(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('subFrameHeader', ctypes.c_uint16),
        ('versions', ctypes.c_uint8),
        ('subDataLength', ctypes.c_uint16),
        ('monitorFloatType', ctypes.c_float * 32),
        ('monitorUint16Type', ctypes.c_uint16 * 32),
        ('monitorInt16Type', ctypes.c_int16 * 32),
        ('subCheckSum', ctypes.c_uint8),
    ]

class Point2DPosition_Linux(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('longitudinal_distance', ctypes.c_float),
        ('lateral_distance', ctypes.c_float),
    ]

class Target_TRACE_Str_Linux(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('track_id', ctypes.c_int32),
        ('longitudinal_distance', ctypes.c_float),
        ('lateral_distance', ctypes.c_float),
        ('vertical_distance', ctypes.c_float),
        ('longitudinal_absolute_velocity', ctypes.c_float),
        ('lateral_absolute_velocity', ctypes.c_float),
        ('longitudinal_relative_velocity', ctypes.c_float),
        ('lateral_relative_velocity', ctypes.c_float),
        ('longitudinal_absolute_acceleration', ctypes.c_float),
        ('lateral_absolute_acceleration', ctypes.c_float),
        ('longitudinal_relative_acceleration', ctypes.c_float),
        ('lateral_relative_acceleration', ctypes.c_float),
        ('length', ctypes.c_float),
        ('width', ctypes.c_float),
        ('height', ctypes.c_float),
        ('heading_angle', ctypes.c_float),
        ('classfication', ctypes.c_int32),
        ('exist_prob', ctypes.c_float),
        ('obstacle_prob', ctypes.c_float),
        ('loss_num', ctypes.c_int32),
        ('points_count', ctypes.c_int32),
        ('age', ctypes.c_int32),
        ('region_id', ctypes.c_int32),
        ('obj_refer_points', Point2DPosition_Linux),
        ('motionstatus', ctypes.c_int32),
        ('class_conf', ctypes.c_float),
        ('height_ground', ctypes.c_float),
        ('location', ctypes.c_float),
        ('measured', ctypes.c_uint32),
        ('refpointdy', ctypes.c_float),
        ('refpointdx', ctypes.c_float),
        ('refpointloc', ctypes.c_float),
        ('dy_vnce', ctypes.c_float),
        ('motionstatusconf', ctypes.c_float),
        ('dx_vnce', ctypes.c_float),
        ('relvy_std', ctypes.c_float),
        ('relvx_std', ctypes.c_float),
        ('valid', ctypes.c_int32),
    ]

class Target_CFAR_Str_Linux(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('longitudinal_distance', ctypes.c_float),
        ('lateral_distance', ctypes.c_float),
        ('vertical_distance', ctypes.c_float),
        ('azimuth', ctypes.c_float),
        ('elevation_angle', ctypes.c_float),
        ('elevation_validy', ctypes.c_uint32),
        ('radial_acceleration', ctypes.c_float),
        ('radial_velocity', ctypes.c_float),
        ('radius', ctypes.c_float),
        ('rcs', ctypes.c_float),
        ('snr', ctypes.c_float),
        ('point_id', ctypes.c_int32),
        ('obj_id', ctypes.c_int32),
        ('motion_status', ctypes.c_int32),
        ('validity', ctypes.c_uint32),
        ('qly', ctypes.c_uint32),
        ('position', ctypes.c_uint32),
    ]

class FreeSpaceData_Str_Linux(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('PointType', ctypes.c_int32),
        ('position', Point2DPosition_Linux),
        ('motion_state', ctypes.c_int32),
    ]

class EthCombinePack_Str_ACC(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ('Protocol_Head', Protocol_Head_Str_ACC),
        ('Frame_Head_Date', Frame_Head_Date_Str_ACC),
        ('RF_ConfigPara_ACC', RF_ConfigPara_Str_ACC),
        ('Radar_Status_Date', Radar_Status_Date_Str_ACC),
        ('MonitorData', MonitorData_DSP_t_ACC),
        ('ECU_DataOut', ECU_Moni_Str_ACC),
        ('ADAS_Monitor', ADAS_Monitor_Str),
        ('TraceMsg', Target_TRACE_Str_ACC),
        ('ClusterMsg', Target_CLUSTER_Str),
        ('CfarMsg', Target_CFAR_Str_ACC),
        ('TempData_Monitor', TempData_Monitor_Str),
        ('totalCheckSum', ctypes.c_uint8),
    ]

print(ctypes.sizeof(Box_Info_Str))
# for attr in dir(EthCombinePack_Str_ACC):
#     if not attr.startswith('__'):
#         # print size of each attribute
#         attr_type = getattr(EthCombinePack_Str_ACC, attr)
#         try:
#             print(attr, attr_type.size)
#         except:
#             pass